# Error codes
RETURN_ERROR_DB_CSV_READ = -1
RETURN_ERROR_DB_DATA_PROCESSING = -2
RETURN_ERROR_DB_CONNECT = -3
RETURN_ERROR_TOSQL = -4

# Global
UNHANDLED_ERROR = -1000

# (MT) Managed Tables
MT_URL_ERROR = -1101

# (UA) User Account Table
UA_INSERT_DUPLICATE = -1201
UA_ERROR_SELECT_FAILED = -1202
UA_DELETE_USER_FAILED = -1203

UA_INSERT_SUCCESS = 1299

# (UA) Login Return Codes
UA_LOGIN_SUCCESS = 1301
UA_LOGIN_FAILED = -1301

# (UAT) User Added Tables
UAT_URL_ERROR = -1401